In [5]:
import numpy as np
import pandas as pd 
import scipy.stats as stats

expected_data = np.array([1]*10 + [0]*10)

print(expected_data)

sample_data = np.array([1]*8 + [0]*10 + [1]*2)

print(sample_data)

cross_calculation = pd.crosstab(expected_data,
                               sample_data,
                               rownames =["Expected"],
                               colnames = ['SampleData'])

print("My Observation Data is : ")
print(cross_calculation)


chi2, p, dof, expected = stats.chi2_contingency(cross_calculation)

print("Chi2 = %f, Pvalue = %f"%(chi2,p))

print(expected)

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1]
My Observation Data is : 
SampleData  0  1
Expected        
0           8  2
1           2  8
Chi2 = 5.000000, Pvalue = 0.025347
[[5. 5.]
 [5. 5.]]
